### ISSUE TITLE
remove appId from "app list" command

### ISSUE THREAD

**Issue by thoro23** [Cap-go/CLI#102]
Hi,
the `app list [appId] [apiKey]` command should list all apps a user has. In the current implementation you can provide an appId which is ignored (at least in the output). Opting here to remove the appId from the command and just have it in the form of `app list [apiKey]`

The appId is used to run a check against it if the apiKey has access to this app. I think that this can be removed and just return all the apps of a user. Is this something you would agree on? I would be willing to create a PR for this.

**Comment by riderx** [comment]
Hey @thoro23 sorry i didn't saw your issue earlier, you are definitely correct, it should be as you said. You can do a Pr if you want, or if you don't have time i fix it

**Comment by riderx** [comment]
Should be fixed !
