### ISSUE TITLE
Feature request: Get channel active bundle from CLI

### ISSUE THREAD

**Issue by simon-acuitymd** [Cap-go/CLI#140]
Maybe this is possible already and I couldn't find it in the docs? I'm looking to update some mobile build scripts we have, and ideally be able to guide the operator through whether they'll be doing an OTA capgo release or a native release. I could detect this if I could combine:
1. Get from capgo the current bundle version for a specific channel (eg `production`)
2. Compare that using a semver comparison against the `package.json` version

I don't see how to do (1) currently - I imagine this could look something like
```
$ npx capgo channel currentVersion [channelName eg "production"]
5.0.1
```
Where the output is just the version number so that I can pipe the output into another script (or offer a `--quiet` option or something to permit easy leveraging into scripts, other capgo CLI commands tend to be verbose in output (which is nice, but harder to use for scripting)). 

Anyway, figured I'd capture the ask :)

**Comment by riderx** [comment]
Thanks @simon-acuitymd for asking, I will bounty it, I believe it's easy to do!
