### ISSUE TITLE
Plugin is not configured in your JavaScript code

### ISSUE THREAD

**Issue by ArunBharathan** [Cap-go/CLI#148]
I have already added notifyAppReady() in my react app and it just works fine but since today 18-09-2023 it show the following error when i try to upload the bundle. so how can i fix this ? 
![Screenshot from 2023-09-18 14-07-01](https://github.com/Cap-go/CLI/assets/13267995/075e15aa-d16f-4945-a797-ace2e04c75fc)
![Screenshot from 2023-09-18 14-07-20](https://github.com/Cap-go/CLI/assets/13267995/adcf0772-b240-445d-af68-82addab12318)

**Comment by hichemfantar** [comment]
Same issue, I also get main.ts file not found. the CLI doesn't detect .tsx files

**Comment by riderx** [comment]
Hey @ArunBharathan thanks for the report, it was due to a missing file extension, tsx,jsx was missing, it has been corrected and fixed  today

**Comment by ArunBharathan** [comment]
Thanks @riderx for addressing the problem

**Comment by hichemfantar** [comment]
fixed by #151
