### ISSUE TITLE
React template main file not detected

### ISSUE THREAD

**Issue by hichemfantar** [Cap-go/CLI#150]
When adding capgo to a react ionic app, it seems that the main.tsx file isn't detected.

1. `Automatic Add "CapacitorUpdater.notifyAppReady()" code and import in io.ionic.starter?`
2. `Yes`
3. `No main.ts, main.js, index.ts or index.js file found, You need to add @capgo/capacitor-updater manually`

![image](https://github.com/Cap-go/CLI/assets/34947993/6e1524ab-0667-40ce-8871-8e0771a6a4f6)

**Comment by riderx** [comment]
Thanks for the report and fixing it !

**Comment by hichemfantar** [comment]
You're welcome!
