### ISSUE TITLE
Error: Automatic build io.ionic.starter with "npm run build"

### ISSUE THREAD

**Issue by hichemfantar** [Cap-go/CLI#152]
I get an error when setting up capgo with a vue app.
- Ionic VueJS Template

1. `Automatic build io.ionic.starter with "npm run build" ?`
2. `Yes`
3. `Something went wrong`

![image](https://github.com/Cap-go/CLI/assets/34947993/ed2075c7-8d87-4980-98c7-488f217ae5ff)

**Comment by riderx** [comment]
Can you run `npx @capgo/cli doctor` and add the report here.

**Comment by hichemfantar** [comment]
running `npx @capgo/cli@latest doctor` gives this result:
```
     💊   Capgo Doctor  💊

 OS: Windows 10 Pro

 Installed Dependencies:

   @capgo/cli: 3.13.27
   @capgo/capacitor-updater: ^5.2.35


✓ Latest Dependencies:


   @capgo/cli: 3.13.27
   @capgo/capacitor-updater: 5.2.35


🚨 Some dependencies are not up to date
```

**Comment by riderx** [comment]
If you do run `m run build` yourself, it works ?
I can see you use windows, I never tried this env this could be linked
