### ISSUE TITLE
Feature request: JSON output for `capgo bundle zip` command

### ISSUE THREAD

**Issue by khamaileon** [Cap-go/CLI#162]
To allow user to easily retrieve bundle checksum and filename, it could be nice to have a JSON output instead of a formatted one.

**Comment by khamaileon** [comment]
Thanks to everyone who worked on this. I just tested it and got a strange result. I've got the text version and the json version all together. Am I missing something?

NODE_ENV=production npx @capgo/cli bundle zip --json
┌  Zipping app.example@1.9.1
│
●  Started from path "dist"
│
●  Zipped 640667 bytes
│
◇  Checksum: b436c6b0
│
◇  Saved to app.example_1.9.1.zip
{
  bundle: '1.9.1',
  filename: 'app.example_1.9.1.zip',
  checksum: 'b436c6b0'
}
│
└  Done ✅

**Comment by WcaleNieWolny** [comment]
@khamaileon I created a [PR](https://github.com/Cap-go/CLI/pull/185) that fixes this weird output
