### ISSUE TITLE
Allow set Disable auto update from CLI

### ISSUE THREAD

**Issue by riderx** [Cap-go/CLI#169]
this new feature is missing from CLI set channel method

**Comment by WcaleNieWolny** [comment]
This is implemented in https://github.com/Cap-go/CLI/pull/170. Algora bot just did not catch that

**Comment by WcaleNieWolny** [comment]
@zcesur my PR got merged, aproved tho algora does not see it. I know that double claim is not something that happens often tho it would be nice if algora listed the second claim

**Comment by riderx** [comment]
/accept https://github.com/Cap-go/CLI/issues/170 @WcaleNieWolny

**Comment by zcesur** [comment]
hey @WcaleNieWolny, @riderx - sorry about the inconvenience here! multi claims are in the roadmap, just didn't get around to it yet

i'll go ahead and handle this payout for you
