### ISSUE TITLE
Fix org upload fail

### ISSUE THREAD

**Issue by riderx** [Cap-go/CLI#215]
if your current or is expired trial or above your plan but you want to upload to another org where plan is ok the CLI will block you because it check the plan of your org.
To fix this we need to check the org of the app and not of the user for commands outside create apps.
Also create should ask what org to upload if you have several orgs

**Comment by WcaleNieWolny** [comment]
@melsonic please take a look at [this](https://github.com/Cap-go/capgo/issues/526). The two system should likely be connected with each other

**Comment by melsonic** [comment]
> @melsonic please take a look at [this](https://github.com/Cap-go/capgo/issues/526). The two system should likely be connected with each other

sure :+1:
