### ISSUE TITLE
Auto-delete fail upload

### ISSUE THREAD

**Issue by riderx** [Cap-go/CLI#243]
When the upload task fails, the backend should auto-delete the version.
This feature has to be secure and does not allow users to delete already uploaded versions.

**Comment by Bhavyajain21** [comment]
Can I be assigned?

**Comment by riderx** [comment]
The backend will refuse the deletion from CLI since users cannot delete themself.
so Capgo app has to be updated in the backend.
The goal here is to have a way for the backend to detect the upload fail and auto delete the version number.
Version number cannot be upload twice, so allow deletion can fix that.
On other side just allow re upload when upload is wasn’t done is another valid option.

**Comment by Sambit003** [comment]
@riderx Can I work on this issue?

**Comment by riderx** [comment]
Sorry it's already done, i did it
