### ISSUE TITLE
Make the CLI init command handle auto-install in project

### ISSUE THREAD

**Issue by riderx** [Cap-go/CLI#275]
Currently, the CLI search for main file to import and call the function and install Capgo.

It could be better to have it check for the most common usecase for :
- Nuxtjs
- NextJs
- SvelteKit
- vue
- react
- svelte

And be able to auto find the main file and add the required line in the project.

**Comment by webbdays** [comment]
@riderx 
can you explain bit more with one of the example,
may be nextjs or react.

**Comment by riderx** [comment]
You have the documentation here: 
https://capgo.app/blog/update-your-capacitor-apps-seamlessly-using-capacitor-updater/#manual-capgo-configuration
basically it needs to add :
```
import { CapacitorUpdater } from '@capgo/capacitor-updater'

CapacitorUpdater.notifyAppReady()
```
To the main file, and be sure the framework build in static.
We already have a basic process in the app.
But it don't work for setup where there is not main file yet etc etc
So the goal here is to make it support most of setup style of each framework

**Comment by animeshd9** [comment]
/attempt #275
Can I take the issue
