### ISSUE TITLE
Cannot init with CapGo

### ISSUE THREAD

**Issue by psq-dannyschnacky** [Cap-go/CLI#281]
Running the init task isn't working

Tried:
`bunx --yes @capgo/cli@latest init [ourApiKey]`
and
`npx @capgo/cli@latest init [ourApiKey]`
with the same result

```
ReferenceError: defaultPm is not defined
```

Both`appName` and `appId` are present in our `capacitor.config.ts`

**Comment by psq-dannyschnacky** [comment]
For slightly more context, we use a workspaces monorepo structure and I'm running this task in our package that contains the capacitor project.

**Comment by riderx** [comment]
Thanks for the report, 
I fixed it
