### ISSUE TITLE
Make s3 upload work with any s3 api not only AWS

### ISSUE THREAD

**Issue by riderx** [Cap-go/CLI#302]

**Comment by rishi-raj-jain** [comment]
Hey @riderx,

What do you mean by any S3 api? Like supporting Cloudflare R2 version of S3 for example?

**Comment by riderx** [comment]
Right now we only let the user provide his own s3 account but many provider do support s3 protocole so we should allow to give or aws account ID or full s3 url :)

**Comment by riderx** [comment]
done
