### ISSUE TITLE
Make CLI init command work on Windows

### ISSUE THREAD

**Issue by riderx** [Cap-go/CLI#303]
the encryption step fail
![CleanShot 2024-06-27 at 20 49 39@2x](https://github.com/Cap-go/CLI/assets/4084527/8c3a833e-ef44-43a0-95ab-41b9ce335ec2)

**Comment by WcaleNieWolny** [comment]
fixed in https://github.com/Cap-go/CLI/commit/86127dc5ceb27310cc3ab0c1aca30b60677c4701
