### ISSUE TITLE
Before upload, check if the checksum is the same and block the user if that the same 

### ISSUE THREAD

**Issue by riderx** [Cap-go/CLI#309]
This is made to stop mistakes
We could also propose to user when upload to build for them

**Comment by hunxjunedo** [comment]
@riderx from my understanding, what we are trying to achieve is that whenever a user trying to upload **directly**, we need first compare the upload's checksum to last uploads checksum to remove any chances of uploading the same thing twice. Is that true ?

**Comment by riderx** [comment]
I just made the feature myself, bounty close.
You can see the implementation here: https://github.com/Cap-go/CLI/commit/0204005b7fffd097f4f46eeb58bce3029c5edb54

**Comment by riderx** [comment]
@monyishh it’s done already
