### ISSUE TITLE
channel set --latest should use version from capacitor.config.json

### ISSUE THREAD

**Issue by danbritt** [Cap-go/CLI#338]
When I create and upload a new bundle, it uses the version value from capacitor.config.json, but when I use the --latest flag with "channel set" to link the bundle to a channel, it uses the version from package.json. I think it would be more consistent if using the --latest flag with "channel set" would use the version from capacitor.config.json

**Comment by WcaleNieWolny** [comment]
Fixed, can you test if it works?

**Comment by danbritt** [comment]
Thanks! Works perfectly
