### ISSUE TITLE
capgo/cli hangs after command

### ISSUE THREAD

**Issue by arendjantetteroo** [Cap-go/CLI#61]
Tested with both `@capgo/cli login`   and @capgo/cli list

It hangs after the output. This causes the gitlab pipeline (and github) to fail. 

I did a git bisect, this behaviour does not appear in 2.3.2, the last version before supabase v2. 

```
78089c7f8b609417b9a6cf340794332f9478b3d8 is the first bad commit
commit 78089c7f8b609417b9a6cf340794332f9478b3d8
Author: martindonadieu <martindonadieu@gmail.com>
Date:   Tue Dec 6 19:15:15 2022 +0800

    fix: upgrade to supabase v2

```

I don't see any changes in the login and list files for this commit, so it seems its something in the supabase client that causes it to hang. 

Tested with 
```
git bisect
npm install && npm run dev
nodejs dist/index.js list
`

**Comment by riderx** [comment]
thanks a lot for the report, i had some issues in my project coming from axios maybe they use it as well, i did upgrade to latest supabase, let see if that fix it
