### ISSUE TITLE
Securing external file url with password

### ISSUE THREAD

**Issue by b-huessner** [Cap-go/CLI#82]
Hi,

We would like to use CapGo for our app distribution, however for privacy reasons we would be forced to use our own fileserver for the zip uploads. While this is supported with the --external flag, as far as I could dicern from the logs, it is not possible to provide login credentials to the zip file. Would that be a possibility to implement?

And if not, is it possible to use the --external flag in conjunction with encrypting the app bundle on an external file server?
While having username and password for the file download would still be great, maybe encrypting the bundle would suffice to adhere to our privacy regulations.

Thanks for your time ; )

**Comment by riderx** [comment]
Hello,

encryption is supported with --external, it was made in this purpose !
You can see a better explaination in the blog:
https://capgo.app/blog/self-hosted-live-updates/

Password / login is not supported since encryption use the best tech possible for privacy purpose.
